{{- if .Values.memcached.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-memcached
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "qfieldcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
  template:
    metadata:
      labels:
        {{- include "qfieldcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: memcached
    spec:
      containers:
        - name: memcached
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-memcached
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "qfieldcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
{{- end }} 