{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qfieldcloud.serviceAccountName" . }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
{{- end }} 