{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-worker
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "qfieldcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "qfieldcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "qfieldcloud.fullname" . }}-worker
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["python", "manage.py", "dequeue"]
          env:
            - name: QFIELDCLOUD_USE_KUBERNETES
              value: {{ .Values.worker.kubernetes.enabled | quote }}
            - name: QFIELDCLOUD_KUBERNETES_NAMESPACE
              value: {{ .Values.worker.kubernetes.namespace | quote }}
            - name: QFIELDCLOUD_QGIS_IMAGE_NAME
              value: "{{ .Values.qgis.image.repository }}:{{ .Values.qgis.image.tag }}"
            - name: QFIELDCLOUD_WORKER_QFIELDCLOUD_URL
              value: {{ .Values.django.settings.workerQfieldcloudUrl | quote }}
            - name: QFIELDCLOUD_TRANSFORMATION_GRIDS_VOLUME_NAME
              value: "/transformation_grids"
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.django.settings.settingsModule | quote }}
            - name: DJANGO_DEBUG
              value: {{ .Values.django.settings.debug | quote }}
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "qfieldcloud.fullname" . }}-django
                  key: secretKey
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ .Values.django.settings.allowedHosts | quote }}
            - name: DJANGO_ACCOUNT_EMAIL_VERIFICATION
              value: {{ .Values.django.settings.accountEmailVerification | quote }}
            - name: DJANGO_USE_I18N
              value: {{ .Values.django.settings.useI18n | quote }}
            - name: DJANGO_LANGUAGE_CODE
              value: {{ .Values.django.settings.defaultLanguage | quote }}
            - name: DJANGO_TIME_ZONE
              value: {{ .Values.django.settings.defaultTimeZone | quote }}
            - name: DJANGO_AUTH_TOKEN_EXPIRATION_HOURS
              value: {{ .Values.django.settings.authTokenExpirationHours | quote }}
            - name: DJANGO_PASSWORD_LOGIN_DISABLED
              value: {{ .Values.django.settings.passwordLoginDisabled | quote }}
            - name: DJANGO_SUBSCRIPTION_MODEL
              value: {{ .Values.django.settings.subscriptionModel | quote }}
            - name: DJANGO_SENTRY_DSN
              value: {{ .Values.django.sentry.dsn | quote }}
            - name: DJANGO_SENTRY_RELEASE
              value: {{ .Values.django.sentry.release | quote }}
            - name: DJANGO_SENTRY_SAMPLE_RATE
              value: {{ .Values.django.sentry.sampleRate | quote }}
            - name: DJANGO_EMAIL_HOST
              value: {{ .Values.django.email.host | quote }}
            - name: DJANGO_EMAIL_USE_TLS
              value: {{ .Values.django.email.useTls | quote }}
            - name: DJANGO_EMAIL_USE_SSL
              value: {{ .Values.django.email.useSsl | quote }}
            - name: DJANGO_EMAIL_PORT
              value: {{ .Values.django.email.port | quote }}
            - name: DJANGO_EMAIL_HOST_USER
              value: {{ .Values.django.email.hostUser | quote }}
            - name: DJANGO_EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qfieldcloud.fullname" . }}-django
                  key: emailPassword
            - name: DJANGO_DEFAULT_FROM_EMAIL
              value: {{ .Values.django.email.defaultFromEmail | quote }}
            - name: DJANGO_STORAGE_TYPE
              value: {{ .Values.django.storage.type | quote }}
            - name: DJANGO_STORAGE_ACCESS_KEY_ID
              value: {{ .Values.django.storage.accessKeyId | quote }}
            - name: DJANGO_STORAGE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "qfieldcloud.fullname" . }}-django
                  key: storageSecretKey
            - name: DJANGO_STORAGE_BUCKET_NAME
              value: {{ .Values.django.storage.bucketName | quote }}
            - name: DJANGO_STORAGE_REGION_NAME
              value: {{ .Values.django.storage.regionName | quote }}
            - name: DJANGO_STORAGE_ENDPOINT_URL
              value: {{ .Values.django.storage.endpointUrl | quote }}
            - name: DJANGO_STORAGE_PROJECT_DEFAULT_STORAGE
              value: {{ .Values.django.storage.projectDefaultStorage | quote }}
            - name: DJANGO_STORAGE_MINIO_API_PORT
              value: {{ .Values.django.storage.minioApiPort | quote }}
            - name: DJANGO_STORAGE_MINIO_BROWSER_PORT
              value: {{ .Values.django.storage.minioBrowserPort | quote }}
            - name: DJANGO_STORAGES_CONFIG
              value: {{ .Values.django.storage.storagesConfig | toJson | quote }}
            - name: DJANGO_DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DJANGO_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DJANGO_DATABASE_NAME
              value: {{ .Values.database.name | quote }}
            - name: DJANGO_DATABASE_USER
              value: {{ .Values.database.user | quote }}
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qfieldcloud.fullname" . }}-database
                  key: password
            - name: DJANGO_DATABASE_SSL_MODE
              value: {{ .Values.database.sslMode | quote }}
            - name: DJANGO_GEODATABASE_HOST
              value: {{ .Values.geodatabase.host | quote }}
            - name: DJANGO_GEODATABASE_PORT
              value: {{ .Values.geodatabase.port | quote }}
            - name: DJANGO_GEODATABASE_NAME
              value: {{ .Values.geodatabase.name | quote }}
            - name: DJANGO_GEODATABASE_USER
              value: {{ .Values.geodatabase.user | quote }}
            - name: DJANGO_GEODATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qfieldcloud.fullname" . }}-geodatabase
                  key: password
            {{- include "qfieldcloud.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-worker
  namespace: {{ .Values.worker.kubernetes.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-worker
  namespace: {{ .Values.worker.kubernetes.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "qfieldcloud.fullname" . }}-worker
subjects:
  - kind: ServiceAccount
    name: {{ include "qfieldcloud.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
{{- end }} 